[build]
  command = "bun run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false
